export enum ChartName {
  COMPARE_ORDERS_AMOUNT,
  COMPARE_ORDERS_INCOME,
  ORDERS_AMOUNT_USING_DIFFERENT_PAYMENT_METHODS,
  ORDERS_AMOUNT_IN_DIFFERENT_HOURS,
  SOLD_DISH_AMOUNT,
  SOLD_DISH_INCOME,
  AVERAGE_COMPLETION_ORDER_TIME_DEPENDS_ON_DISHES_AMOUNT,
  ORDERS_AMOUNT_CONSIDERING_DISHES_AMOUNT_IN_EACH,
}
