server:
  port: 9000
  tomcat:
    threads:
      max: 50
    max-connections: 20

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: RESTAURANT-SERVICE
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant/**
          filters:
            - RewritePath=/restaurant/(?<path>.*), /$\{path}
        - id: EMPLOYEE-SERVICE
          uri: lb://EMPLOYEE-SERVICE
          predicates:
            - Path=/employee/**
          filters:
            - RewritePath=/employee/(?<path>.*), /$\{path}
        - id: NEWS-SERVICE
          uri: lb://NEWS-SERVICE
          predicates:
            - Path=/news/**
          filters:
            - RewritePath=/news/(?<path>.*), /$\{path}
        - id: MAIL-SERVICE
          uri: lb://MAIL-SERVICE
          predicates:
            - Path=/mail/**
          filters:
            - RewritePath=/mail/(?<path>.*), /$\{path}
        - id: MENU-SERVICE
          uri: lb://MENU-SERVICE
          predicates:
            - Path=/menu/**
          filters:
            - RewritePath=/menu/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowed-headers:
              - content-type
              - authorization

springdoc:
  swagger-ui:
    urls:
      - name: restaurant
        url: /v3/api-docs/restaurant
      - name: employee
        url: /v3/api-docs/employee
      - name: news
        url: /v3/api-docs/news
      - name: menu
        url: /v3/api-docs/menu